# NOTE: this example targets the master branch of i3status-rust.
#
# For latest stable version, refer to
# https://github.com/greshake/i3status-rust/blob/v0.22.0/examples/config.toml

[theme]
theme = "gruvbox-dark"
[icons]
icons = "emoji"

# [[block]]
# block = "bluetooth"
# mac = "2C:41:A1:C6:CC:BC"
# format = "$icon $name{$percentage|}"
# disconnected_format = ""
# format_unavailable = "QC35 x"

[[block]]
block = "net"
device = "eth0"
# format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {graph_down:8;M*_b#50}"
interval = 5

[[block]]
block = "cpu"
interval = 1
format = "$icon $barchart $utilization $frequency.eng(width:4, prefix:M, force_prefix:true)"
#format = "$barchart {utilization} {frequency}"

[[block]]
block = "temperature"
format = " $icon $max "
format_alt = " $icon $min min, $max max, $average avg "
info = 85
warning = 95
interval = 1
chip = "k10temp-pci-00c3"

[[block]]
block = "memory"
format = "$icon $mem_used.eng(w:5,prefix:M, force_prefix:true) / $mem_total.eng(w:5,prefix:M, force_prefix:true)"
# format = "{mem_used;M}/{mem_total;M}({mem_total_used_percents})"
# display_type = "memory"
# icons = true
interval = 10
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout "
[block.mappings]
"Finnish (N/A)" = "FI 🇫🇮"
"English (US)" = "US 🇺🇸"


# [[block]]
# block = "battery"
# interval = 10
# format = "$icon $percentage $time"

[[block]]
block = "sound"
format = "$icon {$volume.eng(w:2) |} $output_name "
[block.mappings]
"alsa_output.usb-Vanatoo_Vanatoo_T0-00.analog-stereo" = "Speakers"
"alsa_output.usb-Generic_USB_Audio-00.HiFi__Headphones__sink" = "🎧"
"alsa_output.pci-0000_01_00.1.hdmi-stereo" = "📺"

[[block]]
block= "time"
format = "🕑 $timestamp.datetime(f:'%A %e.%m.%Y %R')"
interval = 1
